version: "2"

services:
        gulp:
                image: node
                working_dir: /data
                command: sh -c 'npm install && npm run serve'
                volumes:
                 - ".:/data"
                ports:
                 - "3000:3000"
                 - "3001:3001"
